### ISSUE TITLE
Meta: Markdown linter

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/action-collection#7]
The Markdown linter we're using is throwing errors.  Not sure if there's a newer version that runs better or if there's a configuration change that we need to make on this repo but would be nice for someone to dig in a bit and see if we can fix this linter config/settings rather than just ignoring the errors it's throwing for the changelog.md

**Comment by jcsparks** [comment]
I think I got them all merged in, let me know if I missed any.

**Comment by timurtripp** [comment]
Looks good, I'll mark this as resolved. Thanks!
